server:
  port: 8090

spring:
  application:
    name: mic-productCategory

  data:
    mongodb:
      uri: mongodb://jfinol02:jfinol02@localhost:27017/micro

logging:
  level:
    org.springframework.data.mongodb: DEBUG



