server:
  port: 8090

spring-doc:
  swagger-ui:
    path: /web/swagger.html
    #http://localhost:3030/swagger-ui-custom.html

spring:
  application:
    name: mic-productcategory

  data:
    mongodb:
      uri: mongodb://jfinol02:jfinol02@localhost:27017/micro
#      database: product
#      username: puser
#      password: f9XFVDqUNECTqkPq2JHD
#      host: localhost
#      port: 27017

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    org.springframework.data.mongodb: DEBUG

app:
  environment: DES
  micro: PRODUCT





