version: '3.1'

services:
  mongo:
    image: mongo:latest
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: product
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  mongodb_data_container: